name: Linting

on:
  pull_request:
    branches:
      - '**'

jobs:
  stylelint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use LTS Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: npm

      - name: Install latest npm
        run: npm install --global npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run stylelint
